Add policy for issues with no activity in over 3 years
Azure/azure-functions-host pull request #10083
Opened 2024-04-30 18:50 UTC by liliankasem

Add "no-recent-activity" label to issues that have not been touched in 3 years. This policy runs every Monday at 10am.

2024-05-01 21:51 UTC, jviau approved these changes

2024-05-01 22:23 UTC, fabiocav approved these changes

2024-05-01 22:37 UTC, mattchenderson requested changes
I seriously dislike requesting action from someone without describing the action for them to take. But the action here is separate from the use of this label anyway. This catches actionable items that have been triaged into the backlog. And it will create re-entrants if authors do come back. I think we need to discuss and rethink.

2024-06-14 23:00 UTC, fabiocav commented
Closing this until we discuss the approach we want to take.

2024-06-14 23:00 UTC, closed without merging