Host Release Prep PR v4.35.0
Azure/azure-functions-host pull request #10269
Opened 2024-07-03 18:34 UTC by v-smanchem

Bumping up the minor version to 4.35.0 and updating the release notes.

### Pull request checklist

**IMPORTANT**: Currently, changes must be backported to the `in-proc` branch to be included in Core Tools and non-Flex deployments.

* [ ] Backporting to the `in-proc` branch is not required
    * Otherwise: Link to backporting PR
* [ ] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] My changes **do not** require diagnostic events changes
    * Otherwise: I have added/updated all related diagnostic events and their documentation (Documentation issue linked to PR)
* [ ] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

2024-07-03 18:37 UTC, kshyju commented on release_notes.md
>  - Language worker channels will not be started during placeholder mode if we are in-process (#10161)
Still missing the release notes entry from https://github.com/Azure/azure-functions-host/pull/10263

2024-07-03 18:39 UTC, kshyju approved these changes

2024-07-03 18:44 UTC, fabiocav requested changes
Release notes still look invalid for the release.

2024-07-03 21:27 UTC, kshyju commented on release_notes.md
>  - Fixed a bug where non HTTP invocation responses were processed by `IHttpProxyService` when HTTP proxying capability is enabled (#9984)
> Fixed a bug where non HTTP invocation responses were processed by `IHttpProxyService` when HTTP proxying capability is enabled (#9984)

This was in 4.34.1 hotfix

2024-07-05 15:06 UTC, kshyju approved these changes

2024-07-05 15:57 UTC, fabiocav approved these changes

2024-07-05 16:39 UTC, merged