Update Middleware package
Azure/azure-functions-host pull request #10492
Opened 2024-09-25 00:11 UTC by pragnagopa

### Issue describing the changes in this PR

Back port https://github.com/Azure/azure-functions-host/pull/10490

### Pull request checklist

**IMPORTANT**: Currently, changes must be backported to the `in-proc` branch to be included in Core Tools and non-Flex deployments.

* [ ] Backporting to the `in-proc` branch is not required
    * Otherwise: Link to backporting PR
* [ ] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] My changes **do not** require diagnostic events changes
    * Otherwise: I have added/updated all related diagnostic events and their documentation (Documentation issue linked to PR)
* [ ] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

2024-09-25 15:53 UTC, mathewc approved these changes

2024-09-25 20:24 UTC, pragnagopa commented
@fabiocav - need help with this PR - from failure logs - https://azfunc.visualstudio.com/public/_build/results?buildId=182319&view=logs&j=d3097984-58ae-595d-5abd-14a5c1707c21&t=9f63de88-fd7b-5bde-e456-e2fce12f3a74

Package is not found? does v3.x branch need an update to the app services nuget feed?

```
D:\a\_work\1\s\src\WebJobs.Script.WebHost\WebJobs.Script.WebHost.csproj : error NU1102: Unable to find package Microsoft.Azure.AppService.Middleware.Functions with version (>= 1.5.5) [D:\a\_work\1\s\test\WebJobs.Script.Tests\WebJobs.Script.Tests.csproj]
D:\a\_work\1\s\src\WebJobs.Script.WebHost\WebJobs.Script.WebHost.csproj : error NU1102:   - Found 2 version(s) in AzureFunctionsTempStaging [ Nearest version: 1.5.1 ] [D:\a\_work\1\s\test\WebJobs.Script.Tests\WebJobs.Script.Tests.csproj]
D:\a\_work\1\s\src\WebJobs.Script.WebHost\WebJobs.Script.WebHost.csproj : error NU1102:   - Found 0 version(s) in nuget.org [D:\a\_work\1\s\test\WebJobs.Script.Tests\WebJobs.Script.Tests.csproj]
D:\a\_work\1\s\src\WebJobs.Script.WebHost\WebJobs.Script.WebHost.csproj : error NU1102:   - Found 0 version(s) in azure-appservice-test [D:\a\_work\1\s\test\WebJobs.Script.Tests\WebJobs.Script.Tests.csproj]
D:\a\_work\1\s\src\WebJobs.Script.WebHost\WebJobs.Script.WebHost.csproj : error NU1102:   - Found 0 version(s) in AzureFunctionsPreRelease [D:\a\_work\1\s\test\WebJobs.Script.Tests\WebJobs.Script.Tests.csproj]
D:\a\_work\1\s\src\WebJobs.Script.WebHost\WebJobs.Script.WebHost.csproj : error NU1102:   - Found 0 version(s) in AzureFunctionsRelease [D:\a\_work\1\s\test\WebJobs.Script.Tests\WebJobs.Script.Tests.csproj]

```

2024-10-18 21:39 UTC, fabiocav requested changes
This PR is introducing the following dependency changes:

```
Changed:
    - Microsoft.Extensions.Configuration.Abstractions.dll: 3.1.9.0/3.100.920.47302 -> 5.0.0.0/5.0.20.51904
    - Microsoft.Extensions.Configuration.dll: 3.1.9.0/3.100.920.47302 -> 5.0.0.0/5.0.20.51904
    - Microsoft.Extensions.DependencyInjection.Abstractions.dll: 3.1.9.0/3.100.920.47302 -> 5.0.0.0/5.0.20.51904
    - Microsoft.Extensions.DependencyInjection.dll: 3.1.9.0/3.100.920.47302 -> 5.0.0.0/5.0.20.51904
    - Microsoft.Extensions.Logging.Abstractions.dll: 3.1.9.0/3.100.920.47302 -> 5.0.0.0/5.0.20.51904
    - Microsoft.Extensions.Logging.dll: 3.1.9.0/3.100.920.47302 -> 5.0.0.0/5.0.20.51904
    - Microsoft.Extensions.Options.dll: 3.1.9.0/3.100.920.47302 -> 5.0.0.0/5.0.20.51904
    - Microsoft.Extensions.Primitives.dll: 3.1.9.0/3.100.920.47302 -> 5.0.0.0/5.0.20.51904
    - Microsoft.IdentityModel.JsonWebTokens.dll: 5.5.0.0/5.5.0.60624 -> 6.32.0.0/6.32.0.40712
    - Microsoft.IdentityModel.Logging.dll: 5.5.0.0/5.5.0.60624 -> 6.32.0.0/6.32.0.40712
    - Microsoft.IdentityModel.Protocols.dll: 5.5.0.0/5.5.0.60624 -> 6.32.0.0/6.32.0.40712
    - Microsoft.IdentityModel.Protocols.OpenIdConnect.dll: 5.5.0.0/5.5.0.60624 -> 6.32.0.0/6.32.0.40712
    - Microsoft.IdentityModel.Tokens.dll: 5.5.0.0/5.5.0.60624 -> 6.32.0.0/6.32.0.40712
    - Newtonsoft.Json.dll: 12.0.0.0/12.0.3.23909 -> 13.0.0.0/13.0.1.25517
    - System.IdentityModel.Tokens.Jwt.dll: 5.5.0.0/5.5.0.60624 -> 6.32.0.0/6.32.0.40712

  Removed:
    - Microsoft.Extensions.Configuration.Binder.dll: 3.1.9.0/3.100.920.47302

  Added:
    - Microsoft.Extensions.Caching.Abstractions.dll: 5.0.0.0/5.0.20.51904
    - Microsoft.Extensions.Caching.Memory.dll: 5.0.0.0/5.0.20.51904
    - Microsoft.IdentityModel.Abstractions.dll: 6.32.0.0/6.32.0.40712
    - Microsoft.IdentityModel.Validators.dll: 6.32.0.0/6.32.0.40712
    - System.Text.Json.dll: 4.0.1.2/4.700.20.21406
```

Some of those are across major versions, so we can't safely bring them.

2024-10-18 21:39 UTC, fabiocav commented on NuGet.config
> +	 <add key="AzureFunctions@internalrelease" value="https://azfunc.pkgs.visualstudio.com/e6a70c92-4128-439f-8012-382fe78d6396/_packaging/AzureFunctions%40internalrelease/nuget/v3/index.json" />
nit: formatting.

2024-11-04 09:52 UTC, closed without merging