Performance improvements
Azure/azure-functions-host pull request #6513
Opened 2020-08-17 21:15 UTC by mathewc

2020-08-17 21:18 UTC, mathewc commented on src/WebJobs.Script.WebHost/Diagnostics/FunctionInstanceLogger.cs
> -                        monitor = new FunctionInstanceMonitor(function, _metrics, item.FunctionInstanceId);
Removing this type completely to remove an object allocation from the invocation path

2020-08-17 21:19 UTC, mathewc commented on src/WebJobs.Script.WebHost/Diagnostics/MetricsEventManager.cs
> -            private ConcurrentDictionary<string, RunningFunctionInfo> _runningFunctions = new ConcurrentDictionary<string, RunningFunctionInfo>();
Use of this concurrent dictionary was causing a "hot lock" to show up in profiles. I've moved to a simpler locking strategy.

2020-08-17 21:21 UTC, mathewc commented on src/WebJobs.Script.WebHost/Diagnostics/MetricsEventManager.cs
> -                if (_runningFunctions.TryRemove(key, out RunningFunctionInfo functionInfo))
We no longer remove from the collection on completion, reducing lock contention. We just raise the completed event. The background timer that is raising in progress events will skip/purge any completed functions.

2020-08-17 21:23 UTC, mathewc commented on src/WebJobs.Script.WebHost/Diagnostics/MetricsEventManager.cs
> -                var value = new RunningFunctionInfo(startedEvent.FunctionMetadata.Name, startedEvent.InvocationId, startedEvent.Timestamp, startedEvent.Success, triggerType);
Removing this type completely. It was just a copy of data we already have in the started event, so we just track those instances directly.

2020-08-17 22:26 UTC, mathewc commented on src/WebJobs.Script/Description/DotNet/DotNetFunctionInvoker.cs
> +            object result = await _methodInvoker.InvokeAsync(null, parameters);
Replacing reflection invoke with call to compiled lambda

2020-08-17 22:27 UTC, mathewc commented on src/WebJobs.Script/Description/DotNet/DotNetFunctionInvoker.cs
> -                result = await ((Task)result).ContinueWith(t => GetTaskResult(t), TaskContinuationOptions.ExecuteSynchronously);
No longer need to use reflection to unwrap the task result

2020-08-17 22:29 UTC, mathewc commented on test/WebJobs.Script.Tests.Integration/WebHostEndToEnd/ProxyEndToEndTests.cs
> +            _hostName = new HostNameProvider(SystemEnvironment.Instance).Value ?? "localhost";
Often on my machine I have a WEBSITE_SITE_NAME env var set which breaks these tests.

2020-08-18 22:31 UTC, paulbatum requested changes
Same feedback as on the associated webjobs PR, there's a few different changes happening here (how the instance logger works, using compiled lambdas), please send as separate PRs.

2020-08-21 17:45 UTC, closed without merging