[DRAFT] All Project Stein Changes So Far
Azure/azure-functions-host pull request #7569
Opened 2021-07-26 19:58 UTC by anandagopal6

### Issue describing the changes in this PR

resolves #issue_for_this_pr

### Pull request checklist

* [ ] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

2021-07-26 22:38 UTC, anandagopal6 commented
/azp run

2021-07-27 21:10 UTC, soninaren requested changes
Requesting nit changes and others that we discussed on the call

2021-07-27 21:10 UTC, soninaren commented on src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs
> +            _initMessage.Capabilities.Add("WorkerIndexing", "true"); // manually add capability for now without touching worker. Assume it is true.
This should be removed

2021-07-27 21:10 UTC, soninaren commented on src/WebJobs.Script.Grpc/Channel/WorkerCapabilities.cs
> +﻿// Copyright (c) .NET Foundation. All rights reserved.
Remove this file

2021-07-27 21:10 UTC, soninaren commented on src/WebJobs.Script/Host/FunctionMetadataManager.cs
> +        private IFunctionMetadataProviderFactory _functionMetadataProviderFactory;
nit: Factory could be readonly

2021-07-27 21:10 UTC, soninaren commented on src/WebJobs.Script/Host/FunctionMetadataProviderFactory.cs
> +
nit: empty line

2021-07-27 21:10 UTC, soninaren commented on src/WebJobs.Script/Host/FunctionMetadataManager.cs
> +        public ImmutableArray<FunctionMetadata> GetFunctionMetadata(bool forceRefresh, bool applyAllowList = true, bool includeCustomProviders = true, IFunctionInvocationDispatcher dispatcher = null,
workerIndexing is unused

2021-07-27 21:10 UTC, soninaren commented on src/WebJobs.Script/Host/FunctionMetadataManager.cs
> +        internal ImmutableArray<FunctionMetadata> LoadFunctionMetadata(bool forceRefresh = false, bool includeCustomProviders = true, IFunctionInvocationDispatcher dispatcher = null, bool workerIndex
workerIndexing is unused

2021-07-28 01:18 UTC, anandagopal6 commented
/azp run

2021-08-11 20:31 UTC, anandagopal6 commented
Closing this in favor of the larger PR with all Stein changes

2021-08-11 20:31 UTC, closed without merging