Validate SKU limits for retries
Azure/azure-functions-host pull request #7788
Opened 2021-10-18 21:42 UTC by alrod

### Issue describing the changes in this PR

resolves #issue_for_this_pr

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

2021-10-19 19:51 UTC, mathewc commented on src/WebJobs.Script/Utility.cs
> +            if (interval.HasValue)
The total retry duration for FixedDelay will be MaxRetryCount * DelayInterval, so likely most customer configurations that can run over would bypass your check. For exponential it seems the same issue exists - MaximumInterval is only for a single retry attempt but we'll actually allow MaxRetryCount of those. What is the ultimate goal of these validations?

Work item had suggested some alternatives, since it's tricky to total max duration in all cases. For example, we could log sku based warnings during retries if the duration goes over.

2021-11-22 11:35 UTC, liliankasem commented
@alrod please link related issue in the PR description :D

2021-11-23 14:05 UTC, liliankasem approved these changes

2021-11-23 14:05 UTC, liliankasem commented on src/WebJobs.Script/Utility.cs
> +            // Validate SKU limits for retries
nit: new line before this comment

2021-11-23 14:05 UTC, liliankasem commented on src/WebJobs.Script/Utility.cs
> +            }
nit: another new line after this brace, it's nice to keep the if expressions separated for easier readability

2021-11-23 14:07 UTC, liliankasem requested changes
Flagging for request changes till Mathew's comment is addressed

2021-11-29 07:57 UTC, closed without merging