Adding nodejs package.json warning when using AzureFiles
Azure/azure-functions-host pull request #7948
Opened 2021-12-03 18:30 UTC by alrod

### Issue describing the changes in this PR

resolves #issue_for_this_pr

### Pull request checklist

* [ ] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

### Additional information

Additional PR information

2021-12-03 19:44 UTC, safihamid commented on src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs
> +            if (_workerRuntime == RpcWorkerConstants.NodeLanguageWorkerName && _environment.AzureFilesAppSettingsExist())
Add a comment of our findings and why cold start could be affected if package.json is missing?

2021-12-03 19:46 UTC, safihamid commented on src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs
> +                        _logger.LogDebug("package.json is not found in Azure Files - cold start for NodeJs can be affected.");
not found at the root of Function App?

2021-12-06 19:43 UTC, safihamid approved these changes
:shipit:

2021-12-07 16:53 UTC, liliankasem commented on src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs
> +            // On reading a js file with funciton code('require') NodeJs tries to find 'package.json' all the way up to the file system root.
```suggestion
            // On reading a js file with function code('require') NodeJs tries to find 'package.json' all the way up to the file system root.
```

2021-12-09 03:44 UTC, fabiocav requested changes
Why is this being added to the host and not logged by the worker? This check doesn't really belong here (even if done in the host, it shouldn't be in this class).

2021-12-16 22:40 UTC, alrod commented
closing in favor:
https://github.com/Azure/azure-functions-nodejs-worker/pull/501

2021-12-16 22:40 UTC, closed without merging