updating host version and release notes
Azure/azure-functions-host pull request #8750
Opened 2022-09-15 18:11 UTC by v-smanchem

2022-09-15 18:36 UTC, VpOfEngineering approved these changes
LGTM

2022-09-16 14:25 UTC, VpOfEngineering requested changes

2022-09-16 14:25 UTC, VpOfEngineering commented on release_notes.md
>  [ [bugs](https://github.com/Azure/azure-functions-host/issues?q=is%3Aissue+milestone%3A%22Functions+Sprint+129%22+label%3Abug+is%3Aclosed) | [features](https://github.com/Azure/azure-functions-host/i
make sure to fix the URL - you can see it still has references to release 129.

2022-09-16 20:40 UTC, VpOfEngineering approved these changes
LGTM

2022-09-21 16:31 UTC, amamounelsayed approved these changes

2022-09-22 14:03 UTC, merged