Add more information to extension validation error messages
Azure/azure-functions-host pull request #9389
Opened 2023-07-12 18:36 UTC by davidmrdavid

I'm currently investigating an IcM where a customer is receiving the following non-blocking exception in Application Insights:

"""
Error building configuration in an external startup class. One or more loaded extensions do not meet the minimum requirements. For more information see https://aka.ms/func-min-extension-versions.
ExtensionStartupType DurableTaskWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.Extensions.DurableTask, Version=2.0.0.0, Culture=neutral, PublicKeyToken=014045d636e89289' does not meet the required minimum version of 2.4.1. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.DurableTask to 2.4.1 or later.
"""

As far as I can tell, the customer is using the latest DF Extension, so they should be passing this check. In order to help with future debugging, I want to augment this error message to include the version of the extension that's triggering this error. This PR does just that.

### Issue describing the changes in this PR

No such issue

### Pull request checklist

* [ ] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] My changes **do not** require diagnostic events changes
    * Otherwise: I have added/updated all related diagnostic events and their documentation (Documentation issue linked to PR)
* [ ] I have added all required tests (Unit tests, E2E tests)

2023-07-12 18:52 UTC, mathewc commented
You checked the "I added tests" box above, but didn't include any tests for your changes. All code changes need tests. There's an existing test suite ScriptStartupTypeDiscovererTests.

2023-07-12 19:01 UTC, mathewc requested changes
Need to add tests, as per my other comment

2023-08-17 18:16 UTC, liliankasem commented
@davidmrdavid - is this PR still required? If so please resolve the blocking feedback or close the PR - thanks!

2023-08-29 20:37 UTC, davidmrdavid commented
@liliankasem: Unfortunately I've been caught up in other threads, so I'll be closing this for now. Thanks

2023-08-29 20:37 UTC, closed without merging