Fix Blob Trigger Error
Azure/azure-functions-host pull request #9419
Opened 2023-07-25 19:43 UTC by Tonewall

Fixing the issue in https://github.com/Azure/azure-functions-host/pull/9385
Http trigger apps are running into the error:
_The Flex Consumption SKU only supports EventGrid as the source for BlobTrigger functions. Please update function 'SimpleHttpRequest' to use EventGrid. For more information see https://aka.ms/blob-trigger-eg._

Issue seems like the check is defaulting to true which runs for all triggers

### Issue describing the changes in this PR

resolves #9386

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] My changes **do not** require diagnostic events changes
    * Otherwise: I have added/updated all related diagnostic events and their documentation (Documentation issue linked to PR)
* [x] I have added all required tests (Unit tests, E2E tests)

2023-07-26 13:10 UTC, pragnagopa commented
@Tonewall - Please see unit tests added in https://github.com/Azure/azure-functions-host/pull/9385/files - increase the test converage to include:
1. Other triggers that are not blob - EventHubTrigger
2.  HttpTrigger + Blob Input + BlobOutput

2023-07-26 13:10 UTC, pragnagopa requested changes
Update tests

2023-07-26 16:13 UTC, CooperLink commented
Cherry-picked MyGet removal

2023-07-27 09:08 UTC, alrod approved these changes
The fix looks good to me.

Not sure why we changed the dependances in [EndToEndTestFixture.cs](https://github.com/Azure/azure-functions-host/pull/9419/files#diff-04152c1b4cd9170781e0677681f72f29135979a50ef2cea6deb481a87eb54e4b)

2023-07-27 16:33 UTC, Tonewall commented
> Update tests

Added test to cover http triggers to not have the error thrown

2023-07-27 18:50 UTC, pragnagopa approved these changes

2023-07-27 18:51 UTC, merged